"""empty message

Revision ID: 0639333c448a
Revises: 416cf3242aa0
Create Date: 2024-03-25 13:48:15.577750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0639333c448a'
down_revision = '416cf3242aa0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firstname', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('lastname', sa.String(length=64), nullable=False))
        batch_op.create_index(batch_op.f('ix_user_firstname'), ['firstname'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_lastname'), ['lastname'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_lastname'))
        batch_op.drop_index(batch_op.f('ix_user_firstname'))
        batch_op.drop_column('lastname')
        batch_op.drop_column('firstname')

    # ### end Alembic commands ###
