"""empty message

Revision ID: 9a53850ddaff
Revises: afb415b2a17b
Create Date: 2024-04-18 12:37:13.707227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a53850ddaff'
down_revision = 'afb415b2a17b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_transactions_transaction_id')
        batch_op.create_index(batch_op.f('ix_transactions_transaction_id'), ['transaction_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_transaction_id'))
        batch_op.create_index('ix_transactions_transaction_id', ['transaction_id'], unique=False)

    # ### end Alembic commands ###
