"""empty message

Revision ID: afb415b2a17b
Revises: 560faaa8800d
Create Date: 2024-04-15 06:33:13.138192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afb415b2a17b'
down_revision = '560faaa8800d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('second_account_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_transactions_second_account_id'), ['second_account_id'], unique=False)
        batch_op.create_foreign_key(None, 'accounts', ['second_account_id'], ['number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_transactions_second_account_id'))
        batch_op.drop_column('second_account_id')

    # ### end Alembic commands ###
